import { ErrorFactory } from "../error"

export const unexpectedEndOfArrayErr = ErrorFactory.create('Unexpected end of array')
export const integerOutOfRangeErr = ErrorFactory.create('Integer out of Range')